name: ARMed Tests

on:
  pull_request:

jobs:
  basic-armed-tests:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - macos-14
          - ubuntu-22.04
        os:
          - linux
          - macos
          - win
        pkg:
          - "pkg@5.8.0"
          - "pkg@5.8.1"
          - "@yao-pkg/pkg@5.10.0"

    steps:
      - name: Checkout action code
        uses: actions/checkout@v3
      - name: Run Pkg Action
        uses: ./
        with:
          entrypoint: bin/test
          os: ${{ matrix.os }}
          upload: false
