name: ARMed Tests

on:
  pull_request:

jobs:
  basic-arm-test:
    runs-on: macos-14
    steps:
      - name: Checkout action code
        uses: actions/checkout@v3
      - name: Run Pkg Action
        uses: ./
        with:
          entrypoint: bin/test
          upload: false
      - name: Test Bin
        run: |
          chmod +x dist/@lando/pkg-action
          dist/@lando/pkg-action --version
          file dist/@lando/pkg-action | grep "Mach-O 64-bit executable arm64"

  basic-cross-os-armed-tests:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - macos-14
          - ubuntu-22.04
        os:
          - linux
          - macos
          - win

    steps:
      - name: Checkout action code
        uses: actions/checkout@v3
      - name: Run Pkg Action
        uses: ./
        with:
          entrypoint: bin/test
          arch: arm64
          os: ${{ matrix.os }}
          upload: false
