name: Test User Inputs

on:
  pull_request:

jobs:
  test-default-inputs:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout action code
        uses: actions/checkout@v2
      - name: Run Pkg Action
        uses: ./
        id: input-tests
        with:
          entrypoint: bin/test.js
          test: true

      - name: "TEST: should use user specified package first"
        if: always()
        run: |
          if [ "${{ steps.default-input-tests.outputs.package }}" == "JOHN" ]; then
            echo "::notice title=TEST PASSED::Package name set from user correctly"
          else
            echo "::error title=TEST FAILED!::Package name not set correctly"
            exit 1
          fi
        shell: bash

      - name: "TEST: should use user specified version first."
        if: always()
        run: |
          if [ "${{ steps.default-input-tests.outputs.version }}" == "47" ]; then
            echo "::notice title=TEST PASSED::Version set from user correctly"
          else
            echo "::error title=TEST FAILED!::Version not set correctly"
            exit 1
          fi
        shell: bash


